// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectNode(arg1, arg2) {
  return window['go']['desktop']['App']['ConnectNode'](arg1, arg2);
}

export function DisconnectNode(arg1) {
  return window['go']['desktop']['App']['DisconnectNode'](arg1);
}

export function GetClusterMonitor() {
  return window['go']['desktop']['App']['GetClusterMonitor']();
}

export function GetLocalMonitor() {
  return window['go']['desktop']['App']['GetLocalMonitor']();
}

export function GetNodes() {
  return window['go']['desktop']['App']['GetNodes']();
}

export function GetRemoteMode() {
  return window['go']['desktop']['App']['GetRemoteMode']();
}

export function GetSavedNodes() {
  return window['go']['desktop']['App']['GetSavedNodes']();
}

export function PgDatabases(arg1, arg2) {
  return window['go']['desktop']['App']['PgDatabases'](arg1, arg2);
}

export function PgDeleteRow(arg1, arg2) {
  return window['go']['desktop']['App']['PgDeleteRow'](arg1, arg2);
}

export function PgInsertRow(arg1, arg2) {
  return window['go']['desktop']['App']['PgInsertRow'](arg1, arg2);
}

export function PgRows(arg1, arg2) {
  return window['go']['desktop']['App']['PgRows'](arg1, arg2);
}

export function PgTables(arg1, arg2) {
  return window['go']['desktop']['App']['PgTables'](arg1, arg2);
}

export function PgUpdateCell(arg1, arg2) {
  return window['go']['desktop']['App']['PgUpdateCell'](arg1, arg2);
}

export function ReconnectNode(arg1) {
  return window['go']['desktop']['App']['ReconnectNode'](arg1);
}

export function RemoveNode(arg1) {
  return window['go']['desktop']['App']['RemoveNode'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetNodePaths(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SetNodePaths'](arg1, arg2, arg3);
}

export function SetRemoteMode(arg1) {
  return window['go']['desktop']['App']['SetRemoteMode'](arg1);
}

export function StartTerminalSession(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['StartTerminalSession'](arg1, arg2, arg3);
}

export function StopTerminalSession(arg1) {
  return window['go']['desktop']['App']['StopTerminalSession'](arg1);
}

export function SyncFilesToNode(arg1, arg2) {
  return window['go']['desktop']['App']['SyncFilesToNode'](arg1, arg2);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['desktop']['App']['WriteTerminalInput'](arg1, arg2);
}
