// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {agentserver} from '../models';

export function CheckAppUpdate():Promise<desktop.UpdateInfo>;

export function ConnectNode(arg1:string,arg2:string):Promise<desktop.NodeInfo>;

export function DisconnectNode(arg1:string):Promise<void>;

export function DownloadAndApplyUpdate():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetClusterMonitor():Promise<Array<desktop.NodeMonitorInfo>>;

export function GetLocalMonitor():Promise<Array<desktop.NodeMonitorInfo>>;

export function GetNodes():Promise<Array<desktop.NodeInfo>>;

export function GetRemoteMode():Promise<boolean>;

export function GetSavedNodes():Promise<Array<desktop.SavedNodeInfo>>;

export function PgDatabases(arg1:string,arg2:agentserver.PgConnReq):Promise<Array<string>>;

export function PgDeleteRow(arg1:string,arg2:agentserver.PgDeleteReq):Promise<number>;

export function PgInsertRow(arg1:string,arg2:agentserver.PgInsertReq):Promise<number>;

export function PgRows(arg1:string,arg2:agentserver.PgRowsReq):Promise<agentserver.PgPage>;

export function PgTables(arg1:string,arg2:agentserver.PgConnReq):Promise<Array<agentserver.PgTable>>;

export function PgUpdateCell(arg1:string,arg2:agentserver.PgUpdateReq):Promise<number>;

export function ReconnectNode(arg1:string):Promise<desktop.NodeInfo>;

export function RemoveNode(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetNodePaths(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRemoteMode(arg1:boolean):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StopTerminalSession(arg1:string):Promise<void>;

export function SyncFilesToNode(arg1:string,arg2:string):Promise<string>;

export function UninstallDesktopApp():Promise<desktop.UninstallResult>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
