// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClusterKillJob(arg1) {
  return window['go']['desktop']['App']['ClusterKillJob'](arg1);
}

export function ClusterSubmitJob(arg1) {
  return window['go']['desktop']['App']['ClusterSubmitJob'](arg1);
}

export function ConnectNode(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ConnectNode'](arg1, arg2, arg3);
}

export function DisconnectNode(arg1) {
  return window['go']['desktop']['App']['DisconnectNode'](arg1);
}

export function GetAppLogCount() {
  return window['go']['desktop']['App']['GetAppLogCount']();
}

export function GetAppLogs(arg1) {
  return window['go']['desktop']['App']['GetAppLogs'](arg1);
}

export function GetClusterCompletedJobs() {
  return window['go']['desktop']['App']['GetClusterCompletedJobs']();
}

export function GetClusterDashboard() {
  return window['go']['desktop']['App']['GetClusterDashboard']();
}

export function GetClusterDevices() {
  return window['go']['desktop']['App']['GetClusterDevices']();
}

export function GetClusterQueuedJobs() {
  return window['go']['desktop']['App']['GetClusterQueuedJobs']();
}

export function GetClusterRunningJobs() {
  return window['go']['desktop']['App']['GetClusterRunningJobs']();
}

export function GetClusterTopology() {
  return window['go']['desktop']['App']['GetClusterTopology']();
}

export function GetCompletedJobs() {
  return window['go']['desktop']['App']['GetCompletedJobs']();
}

export function GetDashboard() {
  return window['go']['desktop']['App']['GetDashboard']();
}

export function GetDevices() {
  return window['go']['desktop']['App']['GetDevices']();
}

export function GetFreeDevices() {
  return window['go']['desktop']['App']['GetFreeDevices']();
}

export function GetJobLogs(arg1, arg2) {
  return window['go']['desktop']['App']['GetJobLogs'](arg1, arg2);
}

export function GetNodes() {
  return window['go']['desktop']['App']['GetNodes']();
}

export function GetQueueLength() {
  return window['go']['desktop']['App']['GetQueueLength']();
}

export function GetQueuedJobs() {
  return window['go']['desktop']['App']['GetQueuedJobs']();
}

export function GetRemoteMode() {
  return window['go']['desktop']['App']['GetRemoteMode']();
}

export function GetRunningJobs() {
  return window['go']['desktop']['App']['GetRunningJobs']();
}

export function GetTopology() {
  return window['go']['desktop']['App']['GetTopology']();
}

export function KillJob(arg1) {
  return window['go']['desktop']['App']['KillJob'](arg1);
}

export function RemoveQueuedJob(arg1) {
  return window['go']['desktop']['App']['RemoveQueuedJob'](arg1);
}

export function SetNodePaths(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SetNodePaths'](arg1, arg2, arg3);
}

export function SetRemoteMode(arg1) {
  return window['go']['desktop']['App']['SetRemoteMode'](arg1);
}

export function SubmitJob(arg1) {
  return window['go']['desktop']['App']['SubmitJob'](arg1);
}

export function SyncFilesToNode(arg1, arg2) {
  return window['go']['desktop']['App']['SyncFilesToNode'](arg1, arg2);
}

export function UpdateQueuedPriority(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateQueuedPriority'](arg1, arg2);
}
