// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function GetDashboard():Promise<desktop.DashboardInfo>;

export function GetDevices():Promise<Array<desktop.DeviceInfo>>;

export function GetFreeDevices():Promise<Array<desktop.DeviceInfo>>;

export function GetQueueLength():Promise<number>;

export function GetRunningJobs():Promise<Array<desktop.JobInfo>>;

export function GetTopology():Promise<desktop.TopologyInfo>;

export function KillJob(arg1:string):Promise<void>;

export function SubmitJob(arg1:desktop.SubmitRequest):Promise<string>;
